package com.longwu.appcode.bean;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AppCategories extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_3_3();
    }

    public static AppCategories getRootAsAppCategories(ByteBuffer _bb) {
        return getRootAsAppCategories(_bb, new AppCategories());
    }

    public static AppCategories getRootAsAppCategories(ByteBuffer _bb, AppCategories obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public AppCategories __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public AppCategory appCategories(int j) {
        return appCategories(new AppCategory(), j);
    }

    public AppCategory appCategories(AppCategory obj, int j) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int appCategoriesLength() {
        int o = __offset(4);
        return o != 0 ? __vector_len(o) : 0;
    }

    public AppCategory.Vector appCategoriesVector() {
        return appCategoriesVector(new AppCategory.Vector());
    }

    public AppCategory.Vector appCategoriesVector(AppCategory.Vector obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public static int createAppCategories(FlatBufferBuilder builder,
                                          int appCategoriesOffset) {
        builder.startTable(1);
        AppCategories.addAppCategories(builder, appCategoriesOffset);
        return AppCategories.endAppCategories(builder);
    }

    public static void startAppCategories(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addAppCategories(FlatBufferBuilder builder, int appCategoriesOffset) {
        builder.addOffset(0, appCategoriesOffset, 0);
    }

    public static int createAppCategoriesVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startAppCategoriesVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endAppCategories(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static void finishAppCategoriesBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset);
    }

    public static void finishSizePrefixedAppCategoriesBuffer(FlatBufferBuilder builder, int offset) {
        builder.finishSizePrefixed(offset);
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public AppCategories get(int j) {
            return get(new AppCategories(), j);
        }

        public AppCategories get(AppCategories obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

