package com.longwu.appcode.bean;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Apps extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static Apps getRootAsApps(ByteBuffer _bb) { return getRootAsApps(_bb, new Apps()); }
  public static Apps getRootAsApps(ByteBuffer _bb, Apps obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Apps __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pkg() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pkgAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pkgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String categorys() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer categorysAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer categorysInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createApps(FlatBufferBuilder builder,
      int pkgOffset,
      int categorysOffset) {
    builder.startTable(2);
    Apps.addCategorys(builder, categorysOffset);
    Apps.addPkg(builder, pkgOffset);
    return Apps.endApps(builder);
  }

  public static void startApps(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPkg(FlatBufferBuilder builder, int pkgOffset) { builder.addOffset(0, pkgOffset, 0); }
  public static void addCategorys(FlatBufferBuilder builder, int categorysOffset) { builder.addOffset(1, categorysOffset, 0); }
  public static int endApps(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Apps get(int j) { return get(new Apps(), j); }
    public Apps get(Apps obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

