// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TestMap extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static TestMap getRootAsTestMap(ByteBuffer _bb) { return getRootAsTestMap(_bb, new TestMap()); }
  public static TestMap getRootAsTestMap(ByteBuffer _bb, TestMap obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TestMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public KeyVaules appCategories(int j) { return appCategories(new KeyVaules(), j); }
  public KeyVaules appCategories(KeyVaules obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int appCategoriesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public KeyVaules.Vector appCategoriesVector() { return appCategoriesVector(new KeyVaules.Vector()); }
  public KeyVaules.Vector appCategoriesVector(KeyVaules.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTestMap(FlatBufferBuilder builder,
      int appCategoriesOffset) {
    builder.startTable(1);
    TestMap.addAppCategories(builder, appCategoriesOffset);
    return TestMap.endTestMap(builder);
  }

  public static void startTestMap(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAppCategories(FlatBufferBuilder builder, int appCategoriesOffset) { builder.addOffset(0, appCategoriesOffset, 0); }
  public static int createAppCategoriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAppCategoriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTestMap(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishTestMapBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedTestMapBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TestMap get(int j) { return get(new TestMap(), j); }
    public TestMap get(TestMap obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

